=head1 Welcome to Sprog

I<Sprog> is a tool for working with data.  It allows you to do all the things
those clever Unix geeks can do with their cryptic command lines but you can now
do it all with point-n-click and drag-n-drop.

A Sprog I<machine> has many similarities to a shell script.  It is built from
small reusable parts (called I<gears>) that are connected together to filter
and massage your data.  Once you have built a machine, you can save it and run
it again and again to automatically perform repetitive tasks.

Here are some more help topics to get you started:

=over 4

=item *

L<Building a machine|Sprog::help::build_machine>

=item *

L<Using the Palette|Sprog::help::palette>

=back
