=head1 Input Gears

An input gear acts as a source of raw data for your machine.  The type of input
gear you select dictates where it can read the data from.  Possible data
sources include reading from a file, a web URL, a database, the clipboard etc.

The 'input' gears are the ones that don't have an input connector.  That might
seem a bit confusing at first but it does make sense (really).

See also: L<filter gears|Sprog::help::filter_gears>,
L<output gear|Sprog::help::output_gears>
